#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Thoshith Ravi

# Short bio or description (displayed in the header)
description: Engineering, Technology, Photography
url: http://www.kennygorman.com

# Permalinks
permalink:        pretty
baseurl:          /
title: 		      thoshithsoch.in

author:
  name:           'Thoshith Ravi'
  url:            https://twitter.com/thoshith

paginate:         5

# Custom vars
version:          1.1.0

markdown: redcarpet
highlighter: pygments
permalink: /:title

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
